// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: path_message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Path struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sections []*Section `protobuf:"bytes,2,rep,name=sections,proto3" json:"sections,omitempty"`
	Turnouts []*Turnout `protobuf:"bytes,3,rep,name=turnouts,proto3" json:"turnouts,omitempty"`
	Signals  []*Signal  `protobuf:"bytes,4,rep,name=signals,proto3" json:"signals,omitempty"`
}

func (x *Path) Reset() {
	*x = Path{}
	if protoimpl.UnsafeEnabled {
		mi := &file_path_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_path_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_path_message_proto_rawDescGZIP(), []int{0}
}

func (x *Path) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Path) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *Path) GetTurnouts() []*Turnout {
	if x != nil {
		return x.Turnouts
	}
	return nil
}

func (x *Path) GetSignals() []*Signal {
	if x != nil {
		return x.Signals
	}
	return nil
}

var File_path_message_proto protoreflect.FileDescriptor

var file_path_message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x61, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x1a, 0x15,
	0x74, 0x75, 0x72, 0x6e, 0x6f, 0x75, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x08, 0x73,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x72, 0x61, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x08, 0x74, 0x75,
	0x72, 0x6e, 0x6f, 0x75, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x72, 0x61, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x54, 0x75, 0x72, 0x6e, 0x6f, 0x75, 0x74, 0x52,
	0x08, 0x74, 0x75, 0x72, 0x6e, 0x6f, 0x75, 0x74, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x61,
	0x63, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x07, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x73, 0x42, 0x24, 0x0a, 0x1a, 0x64, 0x65, 0x76, 0x2e, 0x67, 0x6c, 0x79,
	0x63, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x61, 0x63, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x62, 0x50, 0x01, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_path_message_proto_rawDescOnce sync.Once
	file_path_message_proto_rawDescData = file_path_message_proto_rawDesc
)

func file_path_message_proto_rawDescGZIP() []byte {
	file_path_message_proto_rawDescOnce.Do(func() {
		file_path_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_path_message_proto_rawDescData)
	})
	return file_path_message_proto_rawDescData
}

var file_path_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_path_message_proto_goTypes = []interface{}{
	(*Path)(nil),    // 0: prac.net.Path
	(*Section)(nil), // 1: prac.net.Section
	(*Turnout)(nil), // 2: prac.net.Turnout
	(*Signal)(nil),  // 3: prac.net.Signal
}
var file_path_message_proto_depIdxs = []int32{
	1, // 0: prac.net.Path.sections:type_name -> prac.net.Section
	2, // 1: prac.net.Path.turnouts:type_name -> prac.net.Turnout
	3, // 2: prac.net.Path.signals:type_name -> prac.net.Signal
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_path_message_proto_init() }
func file_path_message_proto_init() {
	if File_path_message_proto != nil {
		return
	}
	file_turnout_message_proto_init()
	file_section_message_proto_init()
	file_signal_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_path_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Path); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_path_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_path_message_proto_goTypes,
		DependencyIndexes: file_path_message_proto_depIdxs,
		MessageInfos:      file_path_message_proto_msgTypes,
	}.Build()
	File_path_message_proto = out.File
	file_path_message_proto_rawDesc = nil
	file_path_message_proto_goTypes = nil
	file_path_message_proto_depIdxs = nil
}
