// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: section_message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Section_SectionState int32

const (
	Section_UNKNOWN  Section_SectionState = 0
	Section_BROKEN   Section_SectionState = 1
	Section_OCCUPIED Section_SectionState = 2
	Section_FREE     Section_SectionState = 3
)

// Enum value maps for Section_SectionState.
var (
	Section_SectionState_name = map[int32]string{
		0: "UNKNOWN",
		1: "BROKEN",
		2: "OCCUPIED",
		3: "FREE",
	}
	Section_SectionState_value = map[string]int32{
		"UNKNOWN":  0,
		"BROKEN":   1,
		"OCCUPIED": 2,
		"FREE":     3,
	}
)

func (x Section_SectionState) Enum() *Section_SectionState {
	p := new(Section_SectionState)
	*p = x
	return p
}

func (x Section_SectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Section_SectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_section_message_proto_enumTypes[0].Descriptor()
}

func (Section_SectionState) Type() protoreflect.EnumType {
	return &file_section_message_proto_enumTypes[0]
}

func (x Section_SectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Section_SectionState.Descriptor instead.
func (Section_SectionState) EnumDescriptor() ([]byte, []int) {
	return file_section_message_proto_rawDescGZIP(), []int{0, 0}
}

type Section struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State Section_SectionState `protobuf:"varint,2,opt,name=state,proto3,enum=prac.net.Section_SectionState" json:"state,omitempty"`
}

func (x *Section) Reset() {
	*x = Section{}
	if protoimpl.UnsafeEnabled {
		mi := &file_section_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_section_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_section_message_proto_rawDescGZIP(), []int{0}
}

func (x *Section) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Section) GetState() Section_SectionState {
	if x != nil {
		return x.State
	}
	return Section_UNKNOWN
}

var File_section_message_proto protoreflect.FileDescriptor

var file_section_message_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x61, 0x63, 0x2e, 0x6e, 0x65,
	0x74, 0x22, 0x90, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70,
	0x72, 0x61, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x3f, 0x0a, 0x0c, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x42, 0x52, 0x4f, 0x4b, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x4f, 0x43, 0x43, 0x55, 0x50, 0x49, 0x45, 0x44, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x52,
	0x45, 0x45, 0x10, 0x03, 0x42, 0x24, 0x0a, 0x1a, 0x64, 0x65, 0x76, 0x2e, 0x67, 0x6c, 0x79, 0x63,
	0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x61, 0x63, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x62, 0x50, 0x01, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_section_message_proto_rawDescOnce sync.Once
	file_section_message_proto_rawDescData = file_section_message_proto_rawDesc
)

func file_section_message_proto_rawDescGZIP() []byte {
	file_section_message_proto_rawDescOnce.Do(func() {
		file_section_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_section_message_proto_rawDescData)
	})
	return file_section_message_proto_rawDescData
}

var file_section_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_section_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_section_message_proto_goTypes = []interface{}{
	(Section_SectionState)(0), // 0: prac.net.Section.SectionState
	(*Section)(nil),           // 1: prac.net.Section
}
var file_section_message_proto_depIdxs = []int32{
	0, // 0: prac.net.Section.state:type_name -> prac.net.Section.SectionState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_section_message_proto_init() }
func file_section_message_proto_init() {
	if File_section_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_section_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Section); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_section_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_section_message_proto_goTypes,
		DependencyIndexes: file_section_message_proto_depIdxs,
		EnumInfos:         file_section_message_proto_enumTypes,
		MessageInfos:      file_section_message_proto_msgTypes,
	}.Build()
	File_section_message_proto = out.File
	file_section_message_proto_rawDesc = nil
	file_section_message_proto_goTypes = nil
	file_section_message_proto_depIdxs = nil
}
