// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: station_service.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SearchPathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buttons *ButtonList `protobuf:"bytes,1,opt,name=buttons,proto3" json:"buttons,omitempty"`
}

func (x *SearchPathRequest) Reset() {
	*x = SearchPathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_station_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPathRequest) ProtoMessage() {}

func (x *SearchPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_station_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPathRequest.ProtoReflect.Descriptor instead.
func (*SearchPathRequest) Descriptor() ([]byte, []int) {
	return file_station_service_proto_rawDescGZIP(), []int{0}
}

func (x *SearchPathRequest) GetButtons() *ButtonList {
	if x != nil {
		return x.Buttons
	}
	return nil
}

type SearchPathResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alive bool  `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	Path  *Path `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *SearchPathResponse) Reset() {
	*x = SearchPathResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_station_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPathResponse) ProtoMessage() {}

func (x *SearchPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_station_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPathResponse.ProtoReflect.Descriptor instead.
func (*SearchPathResponse) Descriptor() ([]byte, []int) {
	return file_station_service_proto_rawDescGZIP(), []int{1}
}

func (x *SearchPathResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *SearchPathResponse) GetPath() *Path {
	if x != nil {
		return x.Path
	}
	return nil
}

var File_station_service_proto protoreflect.FileDescriptor

var file_station_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x61, 0x63, 0x2e, 0x6e, 0x65,
	0x74, 0x1a, 0x19, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x61,
	0x74, 0x68, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x43, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x61, 0x63, 0x2e, 0x6e, 0x65,
	0x74, 0x2e, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x07, 0x62, 0x75,
	0x74, 0x74, 0x6f, 0x6e, 0x73, 0x22, 0x4e, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50,
	0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x6c, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x76,
	0x65, 0x12, 0x22, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x72, 0x61, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x32, 0x5b, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x61, 0x63, 0x2e, 0x6e, 0x65, 0x74,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x61, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x24, 0x0a, 0x1a, 0x64, 0x65, 0x76, 0x2e, 0x67, 0x6c, 0x79, 0x63, 0x69, 0x6e,
	0x65, 0x2e, 0x70, 0x72, 0x61, 0x63, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62,
	0x50, 0x01, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_station_service_proto_rawDescOnce sync.Once
	file_station_service_proto_rawDescData = file_station_service_proto_rawDesc
)

func file_station_service_proto_rawDescGZIP() []byte {
	file_station_service_proto_rawDescOnce.Do(func() {
		file_station_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_station_service_proto_rawDescData)
	})
	return file_station_service_proto_rawDescData
}

var file_station_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_station_service_proto_goTypes = []interface{}{
	(*SearchPathRequest)(nil),  // 0: prac.net.SearchPathRequest
	(*SearchPathResponse)(nil), // 1: prac.net.SearchPathResponse
	(*ButtonList)(nil),         // 2: prac.net.ButtonList
	(*Path)(nil),               // 3: prac.net.Path
}
var file_station_service_proto_depIdxs = []int32{
	2, // 0: prac.net.SearchPathRequest.buttons:type_name -> prac.net.ButtonList
	3, // 1: prac.net.SearchPathResponse.path:type_name -> prac.net.Path
	0, // 2: prac.net.StationService.SearchPath:input_type -> prac.net.SearchPathRequest
	1, // 3: prac.net.StationService.SearchPath:output_type -> prac.net.SearchPathResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_station_service_proto_init() }
func file_station_service_proto_init() {
	if File_station_service_proto != nil {
		return
	}
	file_button_list_message_proto_init()
	file_path_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_station_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_station_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPathResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_station_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_station_service_proto_goTypes,
		DependencyIndexes: file_station_service_proto_depIdxs,
		MessageInfos:      file_station_service_proto_msgTypes,
	}.Build()
	File_station_service_proto = out.File
	file_station_service_proto_rawDesc = nil
	file_station_service_proto_goTypes = nil
	file_station_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StationServiceClient is the client API for StationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StationServiceClient interface {
	SearchPath(ctx context.Context, in *SearchPathRequest, opts ...grpc.CallOption) (*SearchPathResponse, error)
}

type stationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStationServiceClient(cc grpc.ClientConnInterface) StationServiceClient {
	return &stationServiceClient{cc}
}

func (c *stationServiceClient) SearchPath(ctx context.Context, in *SearchPathRequest, opts ...grpc.CallOption) (*SearchPathResponse, error) {
	out := new(SearchPathResponse)
	err := c.cc.Invoke(ctx, "/prac.net.StationService/SearchPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StationServiceServer is the server API for StationService service.
type StationServiceServer interface {
	SearchPath(context.Context, *SearchPathRequest) (*SearchPathResponse, error)
}

// UnimplementedStationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStationServiceServer struct {
}

func (*UnimplementedStationServiceServer) SearchPath(context.Context, *SearchPathRequest) (*SearchPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchPath not implemented")
}

func RegisterStationServiceServer(s *grpc.Server, srv StationServiceServer) {
	s.RegisterService(&_StationService_serviceDesc, srv)
}

func _StationService_SearchPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationServiceServer).SearchPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prac.net.StationService/SearchPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationServiceServer).SearchPath(ctx, req.(*SearchPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prac.net.StationService",
	HandlerType: (*StationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchPath",
			Handler:    _StationService_SearchPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "station_service.proto",
}
