// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: turnout_message.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Turnout_TurnoutState int32

const (
	Turnout_UNKNOWN  Turnout_TurnoutState = 0
	Turnout_NORMAL   Turnout_TurnoutState = 1
	Turnout_REVERSED Turnout_TurnoutState = 2
)

// Enum value maps for Turnout_TurnoutState.
var (
	Turnout_TurnoutState_name = map[int32]string{
		0: "UNKNOWN",
		1: "NORMAL",
		2: "REVERSED",
	}
	Turnout_TurnoutState_value = map[string]int32{
		"UNKNOWN":  0,
		"NORMAL":   1,
		"REVERSED": 2,
	}
)

func (x Turnout_TurnoutState) Enum() *Turnout_TurnoutState {
	p := new(Turnout_TurnoutState)
	*p = x
	return p
}

func (x Turnout_TurnoutState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Turnout_TurnoutState) Descriptor() protoreflect.EnumDescriptor {
	return file_turnout_message_proto_enumTypes[0].Descriptor()
}

func (Turnout_TurnoutState) Type() protoreflect.EnumType {
	return &file_turnout_message_proto_enumTypes[0]
}

func (x Turnout_TurnoutState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Turnout_TurnoutState.Descriptor instead.
func (Turnout_TurnoutState) EnumDescriptor() ([]byte, []int) {
	return file_turnout_message_proto_rawDescGZIP(), []int{0, 0}
}

type Turnout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State Turnout_TurnoutState `protobuf:"varint,2,opt,name=state,proto3,enum=prac.net.Turnout_TurnoutState" json:"state,omitempty"`
}

func (x *Turnout) Reset() {
	*x = Turnout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_turnout_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Turnout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turnout) ProtoMessage() {}

func (x *Turnout) ProtoReflect() protoreflect.Message {
	mi := &file_turnout_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turnout.ProtoReflect.Descriptor instead.
func (*Turnout) Descriptor() ([]byte, []int) {
	return file_turnout_message_proto_rawDescGZIP(), []int{0}
}

func (x *Turnout) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Turnout) GetState() Turnout_TurnoutState {
	if x != nil {
		return x.State
	}
	return Turnout_UNKNOWN
}

var File_turnout_message_proto protoreflect.FileDescriptor

var file_turnout_message_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x75, 0x72, 0x6e, 0x6f, 0x75, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x61, 0x63, 0x2e, 0x6e, 0x65,
	0x74, 0x22, 0x86, 0x01, 0x0a, 0x07, 0x54, 0x75, 0x72, 0x6e, 0x6f, 0x75, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x34, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70,
	0x72, 0x61, 0x63, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x54, 0x75, 0x72, 0x6e, 0x6f, 0x75, 0x74, 0x2e,
	0x54, 0x75, 0x72, 0x6e, 0x6f, 0x75, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x35, 0x0a, 0x0c, 0x54, 0x75, 0x72, 0x6e, 0x6f, 0x75, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x52, 0x45, 0x56, 0x45, 0x52, 0x53, 0x45, 0x44, 0x10, 0x02, 0x42, 0x24, 0x0a, 0x1a, 0x64, 0x65,
	0x76, 0x2e, 0x67, 0x6c, 0x79, 0x63, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x61, 0x63, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x62, 0x50, 0x01, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_turnout_message_proto_rawDescOnce sync.Once
	file_turnout_message_proto_rawDescData = file_turnout_message_proto_rawDesc
)

func file_turnout_message_proto_rawDescGZIP() []byte {
	file_turnout_message_proto_rawDescOnce.Do(func() {
		file_turnout_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_turnout_message_proto_rawDescData)
	})
	return file_turnout_message_proto_rawDescData
}

var file_turnout_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_turnout_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_turnout_message_proto_goTypes = []interface{}{
	(Turnout_TurnoutState)(0), // 0: prac.net.Turnout.TurnoutState
	(*Turnout)(nil),           // 1: prac.net.Turnout
}
var file_turnout_message_proto_depIdxs = []int32{
	0, // 0: prac.net.Turnout.state:type_name -> prac.net.Turnout.TurnoutState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_turnout_message_proto_init() }
func file_turnout_message_proto_init() {
	if File_turnout_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_turnout_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Turnout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_turnout_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_turnout_message_proto_goTypes,
		DependencyIndexes: file_turnout_message_proto_depIdxs,
		EnumInfos:         file_turnout_message_proto_enumTypes,
		MessageInfos:      file_turnout_message_proto_msgTypes,
	}.Build()
	File_turnout_message_proto = out.File
	file_turnout_message_proto_rawDesc = nil
	file_turnout_message_proto_goTypes = nil
	file_turnout_message_proto_depIdxs = nil
}
